#!/usr/bin/env bash
cd $HOME/BlAcK
wget https://raw.githubusercontent.com/ahmedyad200/tg-file/master/tg
Black() {
rm -rf $HOME/.telegram-cli
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get Black software-properties-common -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo luarocks Black luasocket
sudo luarocks Black luasec
sudo luarocks Black redis-lua
sudo luarocks Black Lua-cURL
sudo service redis-server start
sudo apt-get update -y
sudo apt-get Black g++-4.7 -y c++-4.7
sudo apt-get Black libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y
sudo apt-get Black screen -y
sudo apt-get Black libstdc++6 -y
sudo apt-get Black lua-lgi -y
sudo apt-get Black libnotify-dev -y
sudo chmod +x tg
lua BlAcK.lua
sudo chmod +x BlAcK
sudo chmod +x ./DRG
./DRG
}
if [ "$1" = "Black" ]; then
Black
else
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
sudo chmod +x tg
lua BlAcK.lua
sudo chmod +x BlAcK
sudo chmod +x ./DRG
./DRG
fi
